### PR TITLE
Absolute URL in search index

### LINKED ISSUE #1770: BS4: box search not working
Hi,

I am testing the in-development version of `pkgdown` for creating a template (uses BS4) and the search box doesn’t seem to work:
Web: https://dieghernan.github.io/rogtemplate/index.html
Source: https://github.com/dieghernan/rogtemplate

The funny thing is that it seems to work locally, so my first guess is that it should be related with relative/absolute paths.

Am I missing something?

Regards

### PR DESCRIPTION
**Pull request by maelle**
Fix #1770 

Not possible to use the "../" strategy here as the search index is the same for the whole website.

For context, this fixes a wrong assumption about what the root is (not necessarily the production website, e.g. see pkgdown websites hosted on GitHub pages).

### CODE REVIEW

File: R/build-search-docs.R [hunk 1]
```diff
@@ -113,6 +113,14 @@ build_search_index <- function(pkg) {
 
   purrr::compact(index)
 
+  # Make URLs absolute if possible
+  url <- pkg$meta$url %||% "/"
```
Comment (hadley) [inline R/build-search-docs.R:117]: Are you sure this shouldn't be `""`? The url you use in the test doesn't have a trailing slash. Maybe worth testing the case of no default url?

Comment (maelle) [reply R/build-search-docs.R]: You were right! I added a test.

In the test I was surprised I had to make sure the file for both the cases was not the same. I think it's because for other snapshot tests, one does not have to worry about overwriting another snapshot. Good to know. :sweat_smile:
