### PR TITLE
Safely copy images in render_rmarkdown (fixes #602)

### LINKED ISSUE #602: ENOENT on copying files in vignettes subdirectory
In a `crunch` package vignette, we load images from an [`images/` subdirectory of `vignettes/`](https://github.com/Crunch-io/rcrunch/tree/master/vignettes/images). These fail to copy to the built pkgdown site and halt the build:

```
Reading 'vignettes/subtotals.Rmd'
Writing 'articles/subtotals.html'
Error: [ENOENT] Failed to copy '/Users/neal.richardson/Documents/crunch/rcrunch/vignettes/images/manning_knowledge_subtotals.png' to '/Users/neal.richardson/Documents/crunch/rcrunch/docs/articles/images/manning_knowledge_subtotals.png': no such file or directory
```

This is similar to https://github.com/r-lib/pkgdown/issues/569 and https://github.com/r-lib/pkgdown/issues/570; and like said in #570, if you create the `images` subdirectory and retry, it completes successfully. Presumably `build_site()` should make sure this file copying doesn't fail the first time. 

The traceback points to `fs::file_copy()`:

```
7: copyfile_(path_expand(path), path_expand(new_path), isTRUE(overwrite))
6: file_copy(path(path_dir(input_path), ext_path), path(path_dir(output_path), 
       ext_path), overwrite = TRUE)
5: render_rmarkdown(pkg, input = input, output = output_file, output_format = format, 
       output_options = options, quiet = quiet)
4: .f(.x[[i]], ...)
3: purrr::walk(pkg$vignettes$name, build_article, pkg = pkg, quiet = quiet, 
       lazy = lazy)
2: build_articles(pkg, lazy = lazy, override = override, preview = FALSE)
1: pkgdown::build_site()
```

Given #569 / #570, this sounds like a general problem that could merit a general solution, so we might try to resolve this by wrapping `file_copy()` like this:

```
safe_file_copy <- function(path, new_path, ...) {
  fs::dir_create(unique(dirname(new_path)))
  fs::file_copy(path, new_path, ...)
}
```

to ensure that destination directories always exist before trying to copy. Alternatively, we could also just add the `dir_create()` inside `render_rmarkdown()` and fix it for vignettes. Happy to submit a PR that does either (or something else entirely); figured I'd file an issue and get guidance before going too far in one direction.

### PR DESCRIPTION
**Pull request by nealrichardson**
Following https://github.com/r-lib/pkgdown/issues/602, I added a `safe_file_copy()` that creates directories before attempting to move files into them and then used it in the `copy_images` block of `render_rmarkdown()`. The test is a unit test of `safe_file_copy()`; I did not add an end-to-end test with a test package with a vignette with images in subdirectories, but I did verify by doing a clean `build_site()` on the package that failed in #602, and it built successfully with this change.

### CODE REVIEW

File: R/rmarkdown.R [hunk 1]
```diff
@@ -41,7 +41,7 @@ render_rmarkdown <- function(pkg, input, output, ..., copy_images = TRUE, quiet
   if (copy_images) {
     ext <- rmarkdown::find_external_resources(input_path, "UTF-8")
     ext_path <- ext$path[ext$web]
-    file_copy(
+    safe_file_copy(
```
Comment (hadley) [inline R/rmarkdown.R]: I don't think it's worthwhile to create a new function here.

File: tests/testthat/test-build-article.R [hunk 2]
```diff
@@ -0,0 +1,20 @@
+context("build_article")
```
Comment (hadley) [inline tests/testthat/test-build-article.R]: Tests should live in a file with the same name as the `R/` file, so can you please place in `test-rmarkdown.R`

File: tests/testthat/test-build-article.R [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+test_that("safe_file_copy (used in render_rmarkdown) copies files in subdirs", {
```
Comment (hadley) [inline tests/testthat/test-build-article.R]: I think it would be better to create a more holistic test of `render_rmarkdown()`, since it's likely that we will need more in future. Can you please create a simple `.Rmd` file that illustrates the problem?

**Comment by nealrichardson** [comment]
Changes made, ready for re-review.

File: R/rmarkdown.R [hunk 4]
```diff
@@ -41,11 +41,11 @@ render_rmarkdown <- function(pkg, input, output, ..., copy_images = TRUE, quiet
...
     ext_path <- ext$path[ext$web]
-    file_copy(
-      path(path_dir(input_path), ext_path),
-      path(path_dir(output_path), ext_path),
-      overwrite = TRUE
-    )
+    origins <- path(path_dir(input_path), ext_path)
+    destinations <- path(path_dir(output_path), ext_path)
+    # Make sure destination paths exist before copying files there
+    dir_create(unique(dirname(destinations)), recursive = TRUE)
```
Comment (hadley) [inline R/rmarkdown.R]: Can you please use `path_dir()` instead of `dirname()`?

You can also drop `recursive = TRUE` since that's the default

File: tests/testthat/test-rmarkdown.R [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+  tmp <- tempfile()
+  expect_output(
+    render_rmarkdown(
+      list(src_path = test_path(), dst_path = tmp),
+      "vignette-with-img.Rmd",
+      "articles/vignette-with-img.html"
+    )
+  )
+  expect_identical(
+    dir(tmp, recursive = TRUE),
```
Comment (hadley) [inline tests/testthat/test-rmarkdown.R]: Can you please use `dir_ls()` here?

File: R/rmarkdown.R [hunk 6]
```diff
@@ -41,11 +41,11 @@ render_rmarkdown <- function(pkg, input, output, ..., copy_images = TRUE, quiet
   if (copy_images) {
     ext <- rmarkdown::find_external_resources(input_path, "UTF-8")
     ext_path <- ext$path[ext$web]
-    file_copy(
-      path(path_dir(input_path), ext_path),
-      path(path_dir(output_path), ext_path),
-      overwrite = TRUE
-    )
+    origins <- path(path_dir(input_path), ext_path)
```
Comment (hadley) [inline R/rmarkdown.R]: pkgdown uses the `src` and `dst` abbreviations elsewhere

**Comment by nealrichardson** [comment]
Done, PTAL

**Comment by hadley** [comment]
Thanks!
