### PR TITLE
Avoid creation of faulty site

### LINKED ISSUE #2329: FR: use more clickable hyperlinks in error messages
Sorry if this issue is not as focused.

Here is a workflow I sometimes use when working on packages to preview its reference index without rendering everything.

```r
# on  a package without an unititalized `docs` directory.
build_reference_index()
Error in `data_deps()`:
! Run pkgdown::init_site() first.
```
I was wondering if  `pkgdown::init_site()` could be a runnable hyperlink?

```r
# I do as instructed.
pkgdown::init_site()
Error: 'path/to/pkg/docs' is non-empty and not built by pkgdown
```
Unfortunately, there is an error.

I think that with my first call, the docs directory is initiated, but is corrupt..
In this case, maybe suggest users to use `pkgdown::clean_site()` then `pkgdown::init_site()` in the error message? I may have gotten that part wrong.

```r
# running without error
pkgdown::clean_site()
pkgdown::init_site()
#> Copying '../../../AppData/Local/Programs/R/R-4.2.3/library/pkgdown/BS5/assets/link.svg' to 'link.svg'
#> Copying '../../../AppData/Local/Programs/R/R-4.2.3/library/pkgdown/BS5/assets/pkgdown.js' to 'pkgdown.js'
```

Then `build_reference_index()` works.
```r
build_reference_index()
#> Writing 'reference/index.html'
```
I can click on the result after all that.

Maybe my workflow is incorrect, so looking for suggestions. However, if it is something that you think is sensible, could the process be simplified a little, so that possibly `build_reference_index()` work on the first try, or the roadmap to success is a little less bumpy (i.e. adding runnable hyperlinks in error messages that will not error )

Thanks!

Edit: some digging

```r
# with empty state
pkgdown:::is_non_pkgdown_site("docs")
#> FALSE
build_reference_index()
Error in `data_deps()`:
! Run pkgdown::init_site() first.
pkgdown:::is_non_pkgdown_site("docs")
#> TRUE
```

### PR DESCRIPTION
**Pull request by olivroy**
Fixes #2329.

Supersedes #2411 

Applies the suggestions to call `init_site()` earlier.

Will be interesting to see the codecov patch, maybe some messages are no longer reached?

Errors are caused by the fact that `init_site()` is called earlier, which triggers a message.

### CODE REVIEW

File: R/utils-fs.R [hunk 1]
```diff
@@ -50,6 +50,15 @@ file_copy_to <- function(pkg,
   file_copy(from_paths[!eq], to_paths[!eq], overwrite = overwrite)
 }
 
+# Checks init_site() first.
+create_subdir <- function(dest_base, subdir) {
+  if (!fs::dir_exists(dest_base)) {
+    init_site()
```
Comment (olivroy) [inline R/utils-fs.R:56]: I forgot to include `pkg` as an argument here. I will look at the implications locally. Hopefully, not too difficult to fix

**Comment by olivroy** [comment]
@hadley solved. I tripped on the fact that having a default argument the same as the name

i.e. 

```r
f <- function(x = x) {
}
```

creates problem. What is the reason behind that?

**Comment by hadley** [comment]
I forget the details, but because default arguments are evaluated when they're used. For example, this is valid R code:

```R
f <- function(x = y) {
  y <- 10
  x
}
```

File: R/utils-fs.R [hunk 2]
```diff
@@ -50,6 +50,15 @@ file_copy_to <- function(pkg,
   file_copy(from_paths[!eq], to_paths[!eq], overwrite = overwrite)
 }
 
+# Checks init_site() first.
+create_subdir <- function(dest_base, subdir, pkg) {
```
Comment (hadley) [inline R/utils-fs.R:54]: Can you drop the `dest_base` argument and just use `pkg$dst_path`? Then I think it would make the most sense to have `pkg` as the first argument.

Comment (olivroy) [reply R/utils-fs.R]: Looks cleaner indeed!

File: R/init.R [hunk 3]
```diff
@@ -24,8 +24,11 @@ init_site <- function(pkg = ".") {
   pkg <- as_pkgdown(pkg)
 
   if (is_non_pkgdown_site(pkg$dst_path)) {
-    cli::cli_abort(
+    cli::cli_abort(c(
       "{.file {pkg$dst_path}} is non-empty and not built by pkgdown",
+      "!" = "Make sure it contains no important information \\
```
Comment (olivroy) [inline R/init.R:29]: I modified this error message, but it is almost impossible to get there now unless you really want to!

**Comment by hadley** [comment]
Thanks!
