### PR TITLE
fix logic in changelog building

### LINKED ISSUE #1680: Changelog / News Contents (pkgdown dev version)
Hi,

Level one headings are not rendered in the table of contents produced with the dev version of pkgdown.
With usual level 1 heading for release: https://umr1283.github.io/umr1283/news/index.html
image
With release version as level 2 headings: https://umr1283.github.io/umr1283/dev/news/index.html
image

Is that on purpose? if so, I am guessing this will break changelog page for many pkgdown website and will need to be reflected in {usethis} (e.g., use_version functions)

### PR DESCRIPTION
**Pull request by maelle**
Fix #1680 reported by @mcanouil

### CODE REVIEW

File: R/build-news.R [hunk 1]
```diff
@@ -277,30 +277,29 @@ tweak_news_heading <- function(x, version, timeline, bs_version) {
     xml2::xml_find_all(".//h1") %>%
     xml2::xml_set_attr("data-toc-text", version)
 
-  if (is.null(timeline)) {
-    return(x)
```
Comment (maelle) [inline R/build-news.R:281]: with a package not on CRAN nothing happened after this.

**Review by hadley — APPROVED** [review]
