### PR TITLE
fix: badge removal from main content when custom sidebar

### LINKED ISSUE #2239: Fix badge removal from main content when custom sidebar
https://github.com/r-lib/pkgdown/issues/2198#issuecomment-1313744055

### PR DESCRIPTION
**Pull request by maelle**
Fix #2239

### CODE REVIEW

File: R/tweak-homepage.R [hunk 1]
```diff
@@ -48,12 +48,13 @@ tweak_sidebar_html <- function(html, sidebar = TRUE, show_badges = TRUE) {
     return(html)
   }
 
+  # this extracts *and removes* badges from HTML
```
Comment (maelle) [inline R/tweak-homepage.R:51]: I am mislead by the name "extract" actually. I looked at synonyms and maybe "pull out" would make it clearer it removes badges. In theory "extract" should however be clear so it might be my fault!

**Review by hadley — APPROVED** [review]
