### PR TITLE
fix logo removal when the logo is in a link

### LINKED ISSUE #1647: Fail to strip logo if linked
e.g. https://pins.rstudio.com/dev/

Underlying markdown:

```md
# pins <a href='https://pins.rstudio.com'><img src='man/figures/logo.png' align="right" height="139" /></a>
```

### PR DESCRIPTION
**Pull request by maelle**
Fix #1647

### CODE REVIEW

File: R/html-tweak.R [hunk 1]
```diff
@@ -206,12 +206,18 @@ tweak_homepage_html <- function(html,
   # logo
   if (!is.null(logo) && bs_version > 3) {
     # Remove logo if added to h1
-    xml2::xml_remove(
-      xml2::xml_find_first(
-        html,
-        ".//h1/img[contains(@src, 'logo')]"
+    # Simple img
+    logo_node <- xml2::xml_find_first(html, ".//h1/img[contains(@src, 'logo')]")
```
Comment (hadley) [inline R/html-tweak.R:210]: Could you just make it this?

```suggestion
    logo_node <- xml2::xml_find_first(html, ".//h1//img[contains(@src, 'logo')]")
```

But I guess that would leave an empty link which would be confusing

File: R/html-tweak.R [hunk 2]
```diff
@@ -206,12 +206,18 @@ tweak_homepage_html <- function(html,
...
+    if(length(logo_node) > 0) {
```
Comment (hadley) [inline R/html-tweak.R:211]: Are you sure that's correct? I would've thought that `xml2_find_first()` always returns an object of length 1, that is sometimes missing.

Either way, I'd probably structure it as two independent steps:

```R
# Bare image
logo_node <- xml2::xml_find_first(html, ".//h1/img[contains(@src, 'logo')]")
if () xml2::xml_remove(logo_node)

# Image in link
logo_node <- xml2::xml_find_first(html, ".//h1/a/img[contains(@src, 'logo')]")
if () xml2::xml_remove(logo_node)
```


Hmmm, or maybe `xml_find_all` is better because `xml_remove()` applied to an empty nodeset probably does nothing:


```R
# Bare image
xml2::xml_remove(xml2::xml_find_all(html, ".//h1/img[contains(@src, 'logo')]"))

# Image in link
xml2::xml_remove(xml2::xml_find_all(html, ".//h1/a/img[contains(@src, 'logo')]"))
```

File: R/html-tweak.R (hunk 1 above)
Comment (maelle) [reply R/html-tweak.R]: Confusing + bad for accessibility

File: R/html-tweak.R (hunk 2 above)
Comment (maelle) [reply R/html-tweak.R]: Ok, I made a new try.

**Review by hadley — APPROVED** [review]
