### PR TITLE
Apply usual logic to search.json location rather than faulty special one

### LINKED ISSUE #1770: BS4: box search not working
Hi,

I am testing the in-development version of `pkgdown` for creating a template (uses BS4) and the search box doesn’t seem to work:
Web: https://dieghernan.github.io/rogtemplate/index.html
Source: https://github.com/dieghernan/rogtemplate

The funny thing is that it seems to work locally, so my first guess is that it should be related with relative/absolute paths.

Am I missing something?

Regards

### PR DESCRIPTION
**Pull request by maelle**
Fix #1770

### CODE REVIEW

File: R/render.r [hunk 1]
```diff
@@ -46,9 +46,6 @@ render_page <- function(pkg = ".", name, data, path = "", depth = NULL, quiet =
   # Potential opt-out of syntax highlighting CSS
   data$needs_highlight_css <- !isFALSE(pkg$meta[["template"]]$params$highlightcss)
 
-  # Search index location
-  data$`search-index` <- paste0("/", pkg$prefix, "search.json")
```
Comment (maelle) [inline R/render.r:50]: this only worked for packages with their own domain/subdomain. :grimacing:

**Review by hadley — APPROVED** [review]
